# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

RESCOMP = windres
DEFINES +=
INCLUDES += -IArcnumCore/include/GLEW -IArcnumCore/include/GLFW
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS)
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS += -lglfw3.lib -lglew32.lib
LDDEPS +=
ALL_LDFLAGS += $(LDFLAGS) -LArcnumCore/lib/GLEW -LArcnumCore/lib/GLFW -s
LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug)
TARGETDIR = bin/Debug
TARGET = $(TARGETDIR)/ArcnumCoreLib.lib
OBJDIR = obj/Debug/ArcnumCoreLib

else ifeq ($(config),release)
TARGETDIR = bin/Release
TARGET = $(TARGETDIR)/ArcnumCoreLib.lib
OBJDIR = obj/Release/ArcnumCoreLib

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/batcher.o
GENERATED += $(OBJDIR)/bump_allocator.o
GENERATED += $(OBJDIR)/color.o
GENERATED += $(OBJDIR)/component.o
GENERATED += $(OBJDIR)/ecs.o
GENERATED += $(OBJDIR)/entity.o
GENERATED += $(OBJDIR)/event.o
GENERATED += $(OBJDIR)/file.o
GENERATED += $(OBJDIR)/hashmap.o
GENERATED += $(OBJDIR)/iterator.o
GENERATED += $(OBJDIR)/layer.o
GENERATED += $(OBJDIR)/layer_stack.o
GENERATED += $(OBJDIR)/log.o
GENERATED += $(OBJDIR)/map.o
GENERATED += $(OBJDIR)/mat.o
GENERATED += $(OBJDIR)/math.o
GENERATED += $(OBJDIR)/renderer.o
GENERATED += $(OBJDIR)/set.o
GENERATED += $(OBJDIR)/str.o
GENERATED += $(OBJDIR)/sub.o
GENERATED += $(OBJDIR)/system.o
GENERATED += $(OBJDIR)/test.o
GENERATED += $(OBJDIR)/uuid.o
GENERATED += $(OBJDIR)/vec.o
GENERATED += $(OBJDIR)/vector.o
GENERATED += $(OBJDIR)/window.o
OBJECTS += $(OBJDIR)/batcher.o
OBJECTS += $(OBJDIR)/bump_allocator.o
OBJECTS += $(OBJDIR)/color.o
OBJECTS += $(OBJDIR)/component.o
OBJECTS += $(OBJDIR)/ecs.o
OBJECTS += $(OBJDIR)/entity.o
OBJECTS += $(OBJDIR)/event.o
OBJECTS += $(OBJDIR)/file.o
OBJECTS += $(OBJDIR)/hashmap.o
OBJECTS += $(OBJDIR)/iterator.o
OBJECTS += $(OBJDIR)/layer.o
OBJECTS += $(OBJDIR)/layer_stack.o
OBJECTS += $(OBJDIR)/log.o
OBJECTS += $(OBJDIR)/map.o
OBJECTS += $(OBJDIR)/mat.o
OBJECTS += $(OBJDIR)/math.o
OBJECTS += $(OBJDIR)/renderer.o
OBJECTS += $(OBJDIR)/set.o
OBJECTS += $(OBJDIR)/str.o
OBJECTS += $(OBJDIR)/sub.o
OBJECTS += $(OBJDIR)/system.o
OBJECTS += $(OBJDIR)/test.o
OBJECTS += $(OBJDIR)/uuid.o
OBJECTS += $(OBJDIR)/vec.o
OBJECTS += $(OBJDIR)/vector.o
OBJECTS += $(OBJDIR)/window.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking ArcnumCoreLib
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning ArcnumCoreLib
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CC) -x c-header $(ALL_CFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/color.o: ArcnumCore/core/ecs/component/color.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/component.o: ArcnumCore/core/ecs/component/component.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ecs.o: ArcnumCore/core/ecs/ecs.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/entity.o: ArcnumCore/core/ecs/entity/entity.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/uuid.o: ArcnumCore/core/ecs/entity/uuid.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/system.o: ArcnumCore/core/ecs/system/system.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/event.o: ArcnumCore/core/events/event.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sub.o: ArcnumCore/core/events/sub.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/batcher.o: ArcnumCore/core/renderer/batcher.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/layer.o: ArcnumCore/core/renderer/layer.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/layer_stack.o: ArcnumCore/core/renderer/layer_stack.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/renderer.o: ArcnumCore/core/renderer/renderer.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/test.o: ArcnumCore/core/tests/test.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/file.o: ArcnumCore/core/util/data/file.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hashmap.o: ArcnumCore/core/util/data/hashmap.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/iterator.o: ArcnumCore/core/util/data/iterator.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/map.o: ArcnumCore/core/util/data/map.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/set.o: ArcnumCore/core/util/data/set.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/str.o: ArcnumCore/core/util/data/str.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vector.o: ArcnumCore/core/util/data/vector.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/log.o: ArcnumCore/core/util/logging/log.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mat.o: ArcnumCore/core/util/math/mat.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/math.o: ArcnumCore/core/util/math/math.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vec.o: ArcnumCore/core/util/math/vec.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/bump_allocator.o: ArcnumCore/core/util/memory/bump_allocator.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/window.o: ArcnumCore/core/window/window.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif