# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Arcnum_config = debug
  ArcnumCoreLib_config = debug

else ifeq ($(config),release)
  Arcnum_config = release
  ArcnumCoreLib_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Arcnum ArcnumCoreLib

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Arcnum: ArcnumCoreLib
ifneq (,$(Arcnum_config))
	@echo "==== Building Arcnum ($(Arcnum_config)) ===="
	@${MAKE} --no-print-directory -C . -f Arcnum.make config=$(Arcnum_config)
endif

ArcnumCoreLib:
ifneq (,$(ArcnumCoreLib_config))
	@echo "==== Building ArcnumCoreLib ($(ArcnumCoreLib_config)) ===="
	@${MAKE} --no-print-directory -C . -f ArcnumCoreLib.make config=$(ArcnumCoreLib_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Arcnum.make clean
	@${MAKE} --no-print-directory -C . -f ArcnumCoreLib.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Arcnum"
	@echo "   ArcnumCoreLib"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"